### ISSUE TITLE
command line utilities should check that api is not None

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/pyglottolog#4]
Otherwise all the commands fail when ever the command attempts to access `api`. This gives a range of different errors. 

The easiest way to fix this would be to fail [here](https://github.com/clld/pyglottolog/blob/master/src/pyglottolog/__main__.py#L29) but this would mean you can't run pyglottolog without a valid glottolog install. I wasn't sure how to fix this otherwise.

**Comment by xrotwang** [comment]
**All** commands expect `args.repos` to point to a valid clone or export of the repos, so I guess your proposed fix is the right thing to do.

**Comment by xrotwang** [comment]
Ok, not true. We want `glottolog help <cmd>` to work anyway - I guess.
