### ISSUE TITLE
Allow specifying glottolog repos dir with environment variable

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/pyglottolog#6]
This would be very helpful 

```
export GLOTTOLOG=/home/simon/data/glottolog
```

**Comment by xrotwang** [comment]
I'd vote for `GLOTTOLOG_REPOS` or even `GLOTTOLOG_REPOSITORY`. Ok?

**Comment by SimonGreenhill** [comment]
Yep, may as well be most specific  e.g. GLOTTOLOG_REPOSITORY

**Comment by xrotwang** [comment]
I think, I'll do this by adding a `__envvar__` attribute to [`clldutils.apilib.API`](https://github.com/clld/clldutils/blob/7b8587ef5b56a2fc6cafaff90bc5004355c2b13f/src/clldutils/apilib.py#L69-L74), so that the mechanism is then also availabe for other repository APIs.

**Comment by xrotwang** [comment]
Ideally, the name of the environment variable could be inferred somehow - but we already have some inconsistency here with `glottolog`, `concepticon-data` and `Grambank`. So I guess explicit is better than implicit - and we don't even provide a fallback name.

**Comment by xrotwang** [comment]
OTOH, isn't adding
```
alias myglottolog='glottolog --repos=/home/simon/data/glottolog'
```
to `.bashrc` somewhat equivalent to defining an environment variable?

**Comment by SimonGreenhill** [comment]
<NAME>_REPOSITORY?

Re alias vs env var, that's true and I can use that to save you work, but an env variable is more flexible e.g. 

```
export GLOTTOLOG_REPOSITORY=.../3.4 && glottolog newick utoa1244 > utoa1244-3.4.nwk 
export GLOTTOLOG_REPOSITORY=.../3.3 && glottolog newick utoa1244 > utoa1244-3.3.nwk
```

**Comment by SimonGreenhill** [comment]
....although my example may have just talked me out of it -- it's just as easy as:

```
glottolog  --repos=..../3.3 newick utoa1244 > utoa1244-3.4.nwk 
glottolog  --repos=..../3.4 newick utoa1244 > utoa1244-3.4.nwk 
```

**Comment by xrotwang** [comment]
Yes, I think this is really just about ad-hoc shell usage convenience. As soo as you write something in a script, I'd prefer explicitly including repository locations in the script as well.

**Comment by xrotwang** [comment]
And in your particular case, you could also have just one repos location and
```
git checkout vX.Y
```
in between `newick` runs.

**Comment by xrotwang** [comment]
And the problem with making ad-hoc shell usage more convenient is that for just occasional use, being explicit is even more important. E.g. after experimenting with environment variables, aliases and config files for this kind of thing, I always got confused - in particular when things just seemed to work, but not quite.

**Comment by SimonGreenhill** [comment]
yeah ok, I'll close and reopen if it bothers me enough in the future.
